=== hmrc/off-payroll-decision/docs/off-payroll-question-set-schema-strict.json
{
  "id": "https://github.com/hmrc/off-payroll-decision-service#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Strict implementation: everything is required for test data creation use https://github.com/hmrc/off-payroll-decision-service/docs/off-payroll-decision-service.json. This schema defines the input message for the Off Payroll Decision Service, the root object is a QuestionSet",
  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^[0-9]{1,2}[.][0-9]{1,2}[.][0-9]{1,2}-?[a-zA-Z-_]$",
      "enum": ["0.0.1-alpha"]
  },
    "correlationID": {
      "type": "string"
    },
    "personalService": {
      "type": "object",
      "properties": {
        "contractualRightForSubstitute": {
          "type": "boolean"
        },
        "contractrualObligationForSubstitute": {
          "type": "boolean"
        },
        "possibleSubstituteRejection": {
          "type": "boolean"
        },
        "engagerArrangeWorker": {
          "type": "boolean"
        },
        "contractTermsWorkerPaysSubstitute": {
          "type": "boolean"
        },
        "workerSentActualSubstitiute": {
          "type": "boolean"
        },
        "possibleHelper": {
          "type": "boolean"
        },
        "workerSentActualHelper": {
          "type": "boolean"
        },
        "workerPayActualHelper": {
          "type": "boolean"
        }
      }, "required": ["contractualRightForSubstitute", "contractrualObligationForSubstitute", "possibleSubstituteRejection", "engagerArrangeWorker", 
        "contractTermsWorkerPaysSubstitute", "workerSentActualSubstitiute", "possibleHelper", "workerSentActualHelper", "workerPayActualHelper"]
    },
    "control": {
      "type": "object",
      "properties": {
        "toldWhatToDo": {"type": "boolean"},
        "engagerMovingWorker": {"type": "boolean"},
        "workerDecidingHowWorkIsDone": {"type": "boolean"},
        "workerLevelOfExpertise": {
          "type": "string",
          "enum": ["highExperience", "mediumExperience", "lowExperience"]
        },
        "whenWorkHasToBeDone": {
          "type": "string",
          "enum": ["engagerStipulated", "agreedWithEngager", "free", "agreedDeadlines"]
        },
        "workerDecideWhere": {
          "type": "string",
          "enum": ["toldWhere", "freeToDecide", "certainPlace", "workerDecideWhere"]
        }
      }, "required": ["toldWhatToDo", "engagerMovingWorker", "workerDecidingHowWorkIsDone", "whenWorkHasToBeDone", "workerLevelOfExpertise"]
          
    },
    "financialRisk": {
      "type": "object",
      "properties": {
        "provideVehicle": {
          "type": "boolean"
        },
        "engagerPayForVehicle": {
          "type": "boolean"
        },
        "workerNeedEquipment": {
          "type": "boolean"
        },
        "workerProvideEquipment": {
          "type": "boolean"
        },
        "workerProvideConsumablesMaterials": {
          "type": "boolean"
        },
        "engagerPayForConsumablesMaterials": {
          "type": "boolean"        
        },
        "workerIncurExpense": {
          "type": "boolean"
        },
        "engagerPayExpense": {
          "type": "boolean"
        },
        "workerMainIncome": {
          "type": "string",
          "enum": ["regular", "pieceRate", "commisionOnly", "commisionAndBasicSalary", 
            "fixedPrice", "shareProfitLoss", "shareProfitOnly", "invoicedHourlyOrDaily"]
        }
      },
        "required": ["provideVehicle", "engagerPayForVehicle", "workerNeedEquipment", "workerProvideEquipment", 
          "workerProvideConsumablesMaterials", "engagerPayForConsumablesMaterials", "workerIncurExpense", "engagerPayExpense", "workerMainIncome"]
    },
    "businessStructure": {
      "type": "object",
      "properties": {
        "workerVAT": {
          "type": "boolean"
        },
        "businesAccount": {
          "type": "boolean"
        },
        "advertiseForWork": {
          "type": "boolean"
        },
        "businessWebsite": {
          "type": "boolean"
        },
        "workerPayForTraining": {
          "type": "boolean"
        },
        "workerExpenseRunningBusinessPremises": {
          "type": "boolean"
        },
        "workerPaysForInsurance": {
          "type": "boolean"
        }
      },
      "required": [ "workerVAT", "businesAccount", "advertiseForWork", "businessWebsite", "workerPayForTraining", 
        "workerExpenseRunningBusinessPremises", "workerPaysForInsurance"]
    },
     "partOfOrganisation": {
      "type": "object",
      "properties": {
        "workerReceivesBenefits": {
          "type": "boolean"
        },
        "workerAsLineManager": {
          "type": "boolean"
        },
        "contactWithEngagerCustomer": {
          "type": "boolean"
        },
        "workerRepresentsEngagerBusiness": {
          "type": "boolean"
        }
      }, "required": ["workerReceivesBenefits", "workerAsLineManager", "contactWithEngagerCustomer", "workerRepresentsEngagerBusiness"]
    },
    "miscalaneous": {
      "type": "object",
      "properties": {
        "similarWork": true
      }, "required": ["similarWork"]
    }
  },
  "required": [
    "version",
    "correlationID",
    "personalService",
    "control",
    "financialRisk",
    "businessStructure",
    "partOfOrganisation",
    "miscalaneous"
  ]
}

=== hmrc/off-payroll-decision/docs/off-payroll-question-set-sample.json
{
  "version": "0.0.1-alpha",
  "correlationID": "12345",
  "personalService": {
    "contractualRightForSubstitute": true,
    "contractrualObligationForSubstitute": false,
    "possibleSubstituteRejection": false,
    "engagerArrangeWorker": true,
    "contractTermsWorkerPaysSubstitute": false,
    "workerSentActualSubstitiute": true,
    "possibleHelper": true,
    "workerSentActualHelper": false,
    "workerPayActualHelper": false
  },
  "control": {
    "toldWhatToDo": true,
    "engagerMovingWorker": true,
    "workerDecidingHowWorkIsDone": true,
    "whenWorkHasToBeDone": "free",
    "workerLevelOfExpertise": "lowExperience"
  },
  "financialRisk": {
    "provideVehicle": false,
    "engagerPayForVehicle": true,
    "workerNeedEquipment": false,
    "workerProvideEquipment": true,
    "workerProvideConsumablesMaterials": true,
    "engagerPayForConsumablesMaterials": false,
    "workerIncurExpense": true,
    "engagerPayExpense": true,
    "workerMainIncome": "invoicedHourlyOrDaily"
  },
  "businessStructure": {
    "workerVAT": false,
    "businesAccount": false,
    "advertiseForWork": false,
    "businessWebsite": true,
    "workerPayForTraining": false,
    "workerExpenseRunningBusinessPremises": true,
    "workerPaysForInsurance": true
  },
  "partOfOrganisation": {
    "workerReceivesBenefits": false,
    "workerAsLineManager": true,
    "contactWithEngagerCustomer": false,
    "workerRepresentsEngagerBusiness": true
  },
  "miscalaneous": {
    "similarWork": true
  }
}
